export const S = {
  wrap: {
    minHeight: "100vh",
    background: "#fafaf8",
    color: "#1a1a1a",
    fontFamily: "'Inter','Segoe UI',sans-serif",
  },
  header: {
    borderBottom: "1px solid #e8e8e4",
    padding: "16px 20px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#fff",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  body:  { maxWidth: 640, margin: "0 auto", padding: "24px 16px" },
  input: {
    width: "100%",
    background: "#fff",
    border: "1.5px solid #e8e8e4",
    borderRadius: 10,
    padding: "12px 16px",
    fontSize: 16,
    color: "#1a1a1a",
    outline: "none",
    boxSizing: "border-box",
  },
  card: {
    background: "#fff",
    border: "1.5px solid #e8e8e4",
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
  },
  bookCard: {
    background: "#fff",
    border: "1.5px solid #e8e8e4",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  chRow: {
    background: "#fff",
    border: "1.5px solid #e8e8e4",
    borderRadius: 10,
    padding: "12px 16px",
    marginBottom: 8,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  back: {
    background: "none",
    border: "none",
    color: "#888",
    fontSize: 15,
    cursor: "pointer",
    marginBottom: 24,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: 0,
  },
  tag:     { background: "#fce7f3", color: "#db2777", borderRadius: 6, padding: "2px 8px", fontSize: 12, fontWeight: 600 },
  tagWarm: { background: "#fff8f0", color: "#b45309", borderRadius: 6, padding: "2px 8px", fontSize: 12, fontWeight: 600 },
  muted:   { color: "#888", fontSize: 13 },
  label:   { fontSize: 12, fontWeight: 700, color: "#aaa", letterSpacing: 0.8, marginBottom: 10 },
  iconBtn: { background: "none", border: "none", cursor: "pointer", fontSize: 13, padding: "2px 6px", borderRadius: 6 },
  btnPink: {
    background: "#f472b6", border: "none", borderRadius: 10,
    padding: "10px 16px", color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer",
  },
  btnPinkFull: {
    width: "100%", background: "#f472b6", border: "none", borderRadius: 10,
    padding: "12px 16px", color: "#fff", fontSize: 15, fontWeight: 600, cursor: "pointer", marginBottom: 8,
  },
  btnOutlinePink: {
    width: "100%", background: "#fce7f3", border: "none", borderRadius: 10,
    padding: "12px 16px", color: "#db2777", fontSize: 15, fontWeight: 600, cursor: "pointer", marginBottom: 8,
  },
  btnAi: {
    width: "100%", background: "#fff8fb", border: "none", borderRadius: 10,
    padding: "12px 16px", color: "#db2777", fontSize: 15, fontWeight: 600, cursor: "pointer", marginBottom: 8,
  },
  googleBtn: {
    width: "100%", background: "#fff", border: "1.5px solid #e8e8e4", borderRadius: 10,
    padding: "12px 16px", fontSize: 15, fontWeight: 600, cursor: "pointer", marginBottom: 8,
    display: "flex", alignItems: "center", justifyContent: "center", gap: 10, color: "#1a1a1a",
  },
  tabActive: {
    background: "#fce7f3", border: "none", borderRadius: 8, padding: "8px 16px",
    fontSize: 14, fontWeight: 700, color: "#db2777", cursor: "pointer", flex: 1,
  },
  tabInactive: {
    background: "none", border: "none", borderRadius: 8, padding: "8px 16px",
    fontSize: 14, fontWeight: 500, color: "#888", cursor: "pointer", flex: 1,
  },
};
